[package]
name = "branch_hints"
version = "0.1.0"
edition = "2021"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
license = "MIT"
repository = "https://github.com/JSorngard/branch_hints"
description = "Crate that provides `likely` and `unlikely` branch hint functions in stable."

[dependencies]

[dev-dependencies]
rand = "0.8"